dist: trusty
sudo: required
language:
  - c
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
script:
  - ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  - export CC=/usr/bin/gcc-6
  - gcc -v
  - cd generate && run

language: c

branches:
    only:
        - travis
