dist: trusty

language:
  - c

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - doxygen
      - graphviz
      
before_script:
  - npm install -g jsdoc-to-markdown@4.0.1
  - npm install -g moxygen@0.8.0

script:
  - export CC=/usr/bin/gcc-6
  - ls -l ${CC} && ${CC} --version
  - cd generate && ./run && ./verify_clean

branches:
    only:
        - gh-pages
        - /.*/
