dist: trusty

language:
  - c

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6

script:
  - export CC=/usr/bin/gcc-6
  - ls -l ${CC} && ${CC} --version
  - cd generate && ./run

branches:
    only:
        - gh-pages
        - /.*/
