dist: xenial
mono: none
sudo: required
dotnet: 2.2

language:
  - c
  - csharp

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6

before_script:
  - npm install -g jsdoc-to-markdown@4.0.1
  - npm install -g google-closure-compiler@20190528.0.0

script:
  - export CC=/usr/bin/gcc-6
  - ls -l ${CC} && ${CC} --version
  - cd generate && rm -f output/* && ./run && ./verify_clean

branches:
    only:
        - gh-pages
        - /.*/

global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - DOTNET_CLI_TELEMETRY_OPTOUT=1
